package constants

// 日志模板集中管理：业务字段变更时必须同步修改对应模板与调用处。
const (
	LogSrvStarted        = "server started"
	LogSrvShutdown       = "server shutting down"
	LogDBConnected       = "database connected"
	LogDBMigrateFailed   = "database migration failed"
	LogRedisConnected    = "redis connected"
	LogRequestIncoming   = "incoming request"
	LogRequestCompleted  = "request completed"
	LogUserRegistered    = "user registered"
	LogUserLoggedIn      = "user logged in"
	LogUserUpdated       = "user profile updated"
	LogWishCreated       = "wish created"
	LogWishUpdated       = "wish updated"
	LogWishDeleted       = "wish deleted"
	LogWishClaimed       = "wish claimed"
	LogClaimProgress     = "wish claim progress updated"
	LogClaimCompleted    = "wish claim completed"
	LogClaimSubmitted    = "wish claim submitted for publisher confirmation"
	LogClaimApproved     = "wish claim approved by publisher"
	LogClaimRejected     = "wish claim rejected by publisher"
	LogBlessingCreated   = "blessing created"
	LogCapsuleCreated    = "time capsule created"
	LogCapsuleDeleted    = "time capsule deleted"
	LogCapsuleUnlocked   = "time capsule unlocked"
	LogBadgeGranted      = "badge granted"
	LogAuditRecorded     = "audit log recorded"
	LogRateLimited       = "request rate limited"
	LogUnauthorized      = "unauthorized access attempt"
	LogForbidden         = "forbidden access attempt"
	LogInvalidParam      = "invalid request parameter"
	LogNotFound          = "resource not found"
	LogInternalError     = "internal server error"
	LogAuthTokenIssued   = "jwt token issued"
	LogFileUploaded      = "file uploaded to minio"
	LogMinIOInitFailed   = "minio client init failed"
	LogWishLike          = "wish liked"
	LogLeaderboardBuilt  = "leaderboard built"
	LogCapsuleCreateFail = "time capsule creation failed"
	LogSeedAdminCreated  = "default admin seeded"
	LogUploadDenied      = "file upload denied by size or type"
)
